FROM docker:{{ env.version }}

{{ if ["19.03", "19.03-rc", "20.10-rc"] | index(env.version) | not then ( -}}
# git is installed in a separate layer to allow sharing between the "dind" and "git" variants
{{ ) else "" end -}}
RUN apk add --no-cache git
